  export const monthOptions = [
    { value: 1, label: "January" },
    { value: 2, label: "February" },
    { value: 3, label: "March" },
    { value: 4, label: "April" },
    { value: 5, label: "May" },
    { value: 6, label: "June" },
    { value: 7, label: "July" },
    { value: 8, label: "August" },
    { value: 9, label: "September" },
    { value: 10, label: "October" },
    { value: 11, label: "November" },
    { value: 12, label: "December" },
  ];


  






  export const countries = [
    { code: "+1", nationality: "American" },
    { code: "+44", nationality: "British" },
    { code: "+91", nationality: "Indian" },
    { code: "+93", nationality: "Afghan" },
    { code: "+355", nationality: "Albanian" },
    { code: "+213", nationality: "Algerian" },
    { code: "+376", nationality: "Andorran" },
    { code: "+244", nationality: "Angolan" },
    { code: "+672", nationality: "Antarctican" },
    { code: "+54", nationality: "Argentinian" },
    { code: "+374", nationality: "Armenian" },
    { code: "+297", nationality: "Aruban" },
    { code: "+61", nationality: "Australian" },
    { code: "+43", nationality: "Austrian" },
    { code: "+994", nationality: "Azerbaijani" },
    { code: "+973", nationality: "Bahraini" },
    { code: "+880", nationality: "Bangladeshi" },
    { code: "+375", nationality: "Belarusian" },
    { code: "+32", nationality: "Belgian" },
    { code: "+501", nationality: "Belizean" },
    { code: "+229", nationality: "Beninese" },
    { code: "+975", nationality: "Bhutanese" },
    { code: "+591", nationality: "Bolivian" },
    { code: "+387", nationality: "Bosnian" },
    { code: "+267", nationality: "Motswana" },
    { code: "+55", nationality: "Brazilian" },
    { code: "+673", nationality: "Bruneian" },
    { code: "+359", nationality: "Bulgarian" },
    { code: "+226", nationality: "Burkinabe" },
    { code: "+257", nationality: "Burundian" },
    { code: "+855", nationality: "Cambodian" },
    { code: "+237", nationality: "Cameroonian" },
    { code: "+1", nationality: "Canadian" },
    { code: "+238", nationality: "Cape Verdean" },
    { code: "+236", nationality: "Central African" },
    { code: "+235", nationality: "Chadian" },
    { code: "+56", nationality: "Chilean" },
    { code: "+86", nationality: "Chinese" },
    { code: "+57", nationality: "Colombian" },
    { code: "+269", nationality: "Comoran" },
    { code: "+242", nationality: "Congolese" },
    { code: "+506", nationality: "Costa Rican" },
    { code: "+385", nationality: "Croatian" },
    { code: "+53", nationality: "Cuban" },
    { code: "+357", nationality: "Cypriot" },
    { code: "+420", nationality: "Czech" },
    { code: "+45", nationality: "Danish" },
    { code: "+253", nationality: "Djiboutian" },
    { code: "+670", nationality: "Timorese" },
    { code: "+593", nationality: "Ecuadorian" },
    { code: "+20", nationality: "Egyptian" },
    { code: "+503", nationality: "Salvadoran" },
    { code: "+240", nationality: "Equatorial Guinean" },
    { code: "+291", nationality: "Eritrean" },
    { code: "+372", nationality: "Estonian" },
    { code: "+251", nationality: "Ethiopian" },
    { code: "+679", nationality: "Fijian" },
    { code: "+358", nationality: "Finnish" },
    { code: "+33", nationality: "French" },
    { code: "+241", nationality: "Gabonese" },
    { code: "+220", nationality: "Gambian" },
    { code: "+995", nationality: "Georgian" },
    { code: "+49", nationality: "German" },
    { code: "+233", nationality: "Ghanaian" },
    { code: "+30", nationality: "Greek" },
    { code: "+299", nationality: "Greenlandic" },
    { code: "+502", nationality: "Guatemalan" },
    { code: "+224", nationality: "Guinean" },
    { code: "+245", nationality: "Guinea-Bissauan" },
    { code: "+592", nationality: "Guyanese" },
    { code: "+509", nationality: "Haitian" },
    { code: "+504", nationality: "Honduran" },
    { code: "+852", nationality: "Hong Konger" },
    { code: "+36", nationality: "Hungarian" },
    { code: "+354", nationality: "Icelander" },
    { code: "+91", nationality: "Indian" },
    { code: "+62", nationality: "Indonesian" },
    { code: "+98", nationality: "Iranian" },
    { code: "+964", nationality: "Iraqi" },
    { code: "+353", nationality: "Irish" },
    { code: "+972", nationality: "Israeli" },
    { code: "+39", nationality: "Italian" },
    { code: "+225", nationality: "Ivorian" },
    { code: "+81", nationality: "Japanese" },
    { code: "+962", nationality: "Jordanian" },
    { code: "+7", nationality: "Kazakhstani" },
    { code: "+254", nationality: "Kenyan" },
    { code: "+686", nationality: "Kiribatian" },
    { code: "+965", nationality: "Kuwaiti" },
    { code: "+996", nationality: "Kyrgyzstani" },
    { code: "+856", nationality: "Laotian" },
    { code: "+371", nationality: "Latvian" },
    { code: "+961", nationality: "Lebanese" },
    { code: "+266", nationality: "Mosotho" },
    { code: "+231", nationality: "Liberian" },
    { code: "+218", nationality: "Libyan" },
    { code: "+423", nationality: "Liechtensteiner" },
    { code: "+370", nationality: "Lithuanian" },
    { code: "+352", nationality: "Luxembourger" },
    { code: "+853", nationality: "Macanese" },
    { code: "+389", nationality: "Macedonian" },
    { code: "+261", nationality: "Malagasy" },
    { code: "+265", nationality: "Malawian" },
    { code: "+60", nationality: "Malaysian" },
    { code: "+960", nationality: "Maldivian" },
    { code: "+223", nationality: "Malian" },
    { code: "+356", nationality: "Maltese" },
    { code: "+692", nationality: "Marshallese" },
    { code: "+222", nationality: "Mauritanian" },
    { code: "+230", nationality: "Mauritian" },
    { code: "+52", nationality: "Mexican" },
    { code: "+691", nationality: "Micronesian" },
    { code: "+373", nationality: "Moldovan" },
    { code: "+377", nationality: "Monacan" },
    { code: "+976", nationality: "Mongolian" },
    { code: "+382", nationality: "Montenegrin" },
    { code: "+212", nationality: "Moroccan" },
    { code: "+258", nationality: "Mozambican" },
    { code: "+95", nationality: "Burmese" },
    { code: "+264", nationality: "Namibian" },
    { code: "+674", nationality: "Nauruan" },
    { code: "+977", nationality: "Nepalese" },
    { code: "+31", nationality: "Dutch" },
    { code: "+64", nationality: "New Zealander" },
    { code: "+505", nationality: "Nicaraguan" },
    { code: "+227", nationality: "Nigerien" },
    { code: "+234", nationality: "Nigerian" },
    { code: "+850", nationality: "North Korean" },
    { code: "+47", nationality: "Norwegian" },
    { code: "+968", nationality: "Omani" },
    { code: "+92", nationality: "Pakistani" },
    { code: "+680", nationality: "Palauan" },
    { code: "+507", nationality: "Panamanian" },
    { code: "+675", nationality: "Papua New Guinean" },
    { code: "+595", nationality: "Paraguayan" },
    { code: "+51", nationality: "Peruvian" },
    { code: "+63", nationality: "Filipino" },
    { code: "+48", nationality: "Polish" },
    { code: "+351", nationality: "Portuguese" },
    { code: "+974", nationality: "Qatari" },
    { code: "+40", nationality: "Romanian" },
    { code: "+7", nationality: "Russian" },
    { code: "+250", nationality: "Rwandan" },
    { code: "+685", nationality: "Samoan" },
    { code: "+378", nationality: "San Marinese" },
    { code: "+239", nationality: "Sao Tomean" },
    { code: "+966", nationality: "Saudi Arabian" },
    { code: "+221", nationality: "Senegalese" },
    { code: "+381", nationality: "Serbian" },
    { code: "+248", nationality: "Seychellois" },
    { code: "+232", nationality: "Sierra Leonean" },
    { code: "+65", nationality: "Singaporean" },
    { code: "+421", nationality: "Slovak" },
    { code: "+386", nationality: "Slovenian" },
    { code: "+677", nationality: "Solomon Islander" },
    { code: "+252", nationality: "Somali" },
    { code: "+27", nationality: "South African" },
    { code: "+82", nationality: "South Korean" },
    { code: "+211", nationality: "South Sudanese" },
    { code: "+34", nationality: "Spanish" },
    { code: "+94", nationality: "Sri Lankan" },
    { code: "+249", nationality: "Sudanese" },
    { code: "+597", nationality: "Surinamese" },
    { code: "+268", nationality: "Swazi" },
    { code: "+46", nationality: "Swedish" },
    { code: "+41", nationality: "Swiss" },
    { code: "+963", nationality: "Syrian" },
    { code: "+886", nationality: "Taiwanese" },
    { code: "+992", nationality: "Tajikistani" },
    { code: "+255", nationality: "Tanzanian" },
    { code: "+66", nationality: "Thai" },
    { code: "+670", nationality: "Timorese" },
    { code: "+228", nationality: "Togolese" },
    { code: "+676", nationality: "Tongan" },
    { code: "+216", nationality: "Tunisian" },
    { code: "+90", nationality: "Turkish" },
    { code: "+993", nationality: "Turkmen" },
    { code: "+688", nationality: "Tuvaluan" },
    { code: "+256", nationality: "Ugandan" },
    { code: "+380", nationality: "Ukrainian" },
    { code: "+971", nationality: "Emirati" },
    { code: "+598", nationality: "Uruguayan" },
    { code: "+998", nationality: "Uzbekistani" },
    { code: "+678", nationality: "Ni-Vanuatu" },
    { code: "+379", nationality: "Vatican" },
    { code: "+58", nationality: "Venezuelan" },
    { code: "+84", nationality: "Vietnamese" },
    { code: "+967", nationality: "Yemeni" },
    { code: "+260", nationality: "Zambian" },
    { code: "+263", nationality: "Zimbabwean" },
  ];
  
